site_name: AVstack-api
site_url: https://avstack.org
theme:
  name: material

plugins:
  - search  # To have search functionality on the document
  - mkdocstrings  # To generate documentation from the code docstrings

nav:
  - About:
    - Installation: about/installation.md
    - License: about/license.md
    - Release Notes: about/release-notes.md