---
client:
  rate: 20

display:
  # use defaults...

world:
  n_random_vehicles: 200
  n_random_walkers: 0

recorder:
  record_truth: false

infrastructure:
  # use defaults...

ego:
  idx_spawn: 'random'
  idx_vehicle: 'lincoln'
  idx_vehicle: 0
  idx_destination: 'random'
  roaming: true
  autopilot: false
  respawn_on_done: true
  max_speed: 20  # m/s
  sensors:
    - camera 0:
        name: 'camera'
        save: false
    - gnss 0:
        name: 'gnss'
        save: false
    - imu 0:
        name: 'imu'
        save: false
    - lidar 0:
        name: 'lidar'
        save: false
        attributes:
          sensor_tick: 0.10
          channels: 32
          rotation_frequency: 20  # needs to be the same as sim rate
          range: 100.0
        noise: {}
        transform:
          location:
            x: -0.5
            y: 0
            z: 1.8