---
client:
  rate: 20

display:
  enabled: false

world:
  n_random_vehicles: 300
  n_random_walkers: 0

recorder:
  record_truth: true

infrastructure:
  # use defaults...

ego:
  idx_spawn: 'randint'
  idx_vehicle: 'lincoln'
  idx_destination: null
  roaming: false
  autopilot: true
  respawn_on_done: true
  max_speed: 30
  sensors:
    - camera 0:
        name: 'CAM_FRONT'
        attributes:
          sensor_tick: 0.10
          fov: 90
          image_size_x: 1600
          image_size_y: 900
        save: true
        noise: {}
        transform:
          location:
            x: 1.6
            y: 0
            z: 1.6
          rotation:
            pitch: 0
            yaw: 0
            roll: 0
    - semsegcam 0:
        name: 'CAM_FRONT_SEMSEG'
        attributes:
          sensor_tick: 0.10
          fov: 90
          image_size_x: 1600
          image_size_y: 900
        save: true
        noise: {}
        transform:
          location:
            x: 1.6
            y: 0
            z: 1.6
          rotation:
            pitch: 0
            yaw: 0
            roll: 0
    - depthcam 0:
        name: 'CAM_FRONT_DEPTH'
        attributes:
          sensor_tick: 0.10
          fov: 90
          image_size_x: 1600
          image_size_y: 900
        save: true
        noise: {}
        transform:
          location:
            x: 1.6
            y: 0
            z: 1.6
          rotation:
            pitch: 0
            yaw: 0
            roll: 0
    - camera 1:
        name: 'CAM_BACK'
        attributes:
          sensor_tick: 0.10
          fov: 90
          image_size_x: 1600
          image_size_y: 900
        save: true
        noise: {}
        transform:
          location:
            x: -1.6
            y: 0
            z: 1.6
          rotation:
            pitch: 0
            yaw: 180
            roll: 0
    - semsegcam 1:
        name: 'CAM_BACK_SEMSEG'
        attributes:
          sensor_tick: 0.10
          fov: 90
          image_size_x: 1600
          image_size_y: 900
        save: true
        noise: {}
        transform:
          location:
            x: -1.6
            y: 0
            z: 1.6
          rotation:
            pitch: 0
            yaw: 180
            roll: 0
    - depthcam 1:
        name: 'CAM_BACK_DEPTH'
        attributes:
          sensor_tick: 0.10
          fov: 90
          image_size_x: 1600
          image_size_y: 900
        save: true
        noise: {}
        transform:
          location:
            x: -1.6
            y: 0
            z: 1.6
          rotation:
            pitch: 0
            yaw: 180
            roll: 0
    - camera 2:
        name: 'CAM_FRONT_RIGHT'
        attributes:
          sensor_tick: 0.10
          fov: 90
          image_size_x: 1600
          image_size_y: 900
        save: true
        noise: {}
        transform:
          location:
            x: 1.0
            y: 1.0
            z: 1.6
          rotation:
            pitch: 0
            yaw: 90
            roll: 0
    - semsegcam 2:
        name: 'CAM_FRONT_RIGHT_SEMSEG'
        attributes:
          sensor_tick: 0.10
          fov: 90
          image_size_x: 1600
          image_size_y: 900
        save: true
        noise: {}
        transform:
          location:
            x: 1.0
            y: 1.0
            z: 1.6
          rotation:
            pitch: 0
            yaw: 90
            roll: 0
    - depthcam 2:
        name: 'CAM_FRONT_RIGHT_DEPTH'
        attributes:
          sensor_tick: 0.10
          fov: 90
          image_size_x: 1600
          image_size_y: 900
        save: true
        noise: {}
        transform:
          location:
            x: 1.0
            y: 1.0
            z: 1.6
          rotation:
            pitch: 0
            yaw: 90
            roll: 0
    - camera 3:
        name: 'CAM_FRONT_LEFT'
        attributes:
          sensor_tick: 0.10
          fov: 90
          image_size_x: 1600
          image_size_y: 900
        save: true
        noise: {}
        transform:
          location:
            x: 1.0
            y: -1.0
            z: 1.6
          rotation:
            pitch: 0
            yaw: -90
            roll: 0
    - semsegcam 3:
        name: 'CAM_FRONT_LEFT_SEMSEG'
        attributes:
          sensor_tick: 0.10
          fov: 90
          image_size_x: 1600
          image_size_y: 900
        save: true
        noise: {}
        transform:
          location:
            x: 1.0
            y: -1.0
            z: 1.6
          rotation:
            pitch: 0
            yaw: -90
            roll: 0
    - depthcam 3:
        name: 'CAM_FRONT_LEFT_DEPTH'
        attributes:
          sensor_tick: 0.10
          fov: 90
          image_size_x: 1600
          image_size_y: 900
        save: true
        noise: {}
        transform:
          location:
            x: 1.0
            y: -1.0
            z: 1.6
          rotation:
            pitch: 0
            yaw: -90
            roll: 0
    - lidar 0:
        name: 'LIDAR_TOP'
        save: true
        attributes:
          sensor_tick: 0.10
          channels: 32
          rotation_frequency: 20  # needs to be the same as sim rate
          range: 100.0
        noise: {}
        transform:
          location:
            x: -0.5
            y: 0
            z: 1.8
    - radar 0:
        name: "RADAR_FRONT"
        save: true
        attributes:
          sensor_tick: 0.10
          horizontal_fov: 30.0
          vertical_fov: 30.0
          points_per_second: 1500
          range: 100.0
        noise: {}
        transform:  # same as the lidar sensor
          location:
            x: -0.5
            y: 0
            z: 1.8